#!/bin/bash

if [ -z $1 ]
then
	echo -e "\e[31mPlease provide command to call\e[0m"
	echo -e "format \e[32mcommand\e[0m or \e[32mchannel command\e[0m"
else
	if [ -z $2 ]
	then
		curl https://api.particle.io/v1/devices/events -d "name=chtapodiEcho" -d "data=$1" -d "private=false" -d "ttl=60" -d access_token="5e6258fe38fd74782b03e54885850847c40517d7" &> /dev/null
		echo -e "calling \e[32m"$1"\e[0m"
	else
		curl https://api.particle.io/v1/devices/events -d "name=$1" -d "data=$2" -d "private=false" -d "ttl=60" -d access_token="5e6258fe38fd74782b03e54885850847c40517d7" &> /dev/null
		echo -e "calling \e[32m"$2"\e[0m on \e[32m"$1"\e[0m"
	fi
fi
