#!/bin/bash

if [ -z $1 ]
then
	echo -e "\e[31mPlease provide command to call\e[0m"
else
	curl https://api.particle.io/v1/devices/events -d "name=chtapodi" -d "data=$1" -d "private=false" -d "ttl=60" -d access_token=[access token here] &> /dev/null
	echo -e "calling \e[32m"$1"\e[0m"
fi
