#!/bin/bash

if [[ $1 == "-r" ]]
then
	if [ -z $2 ]
	then
		count=$(find . | wc -l)
	else
		count=$(find $2 | wc -l)
	fi
else
	if [ -z $1 ]
	then
		count=$(ls -Al | wc -l)
	else
		count=$(ls -Al $1 | wc -l)
	fi
fi
count=$(($count -1))

echo $count
