#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
export PATH="$PATH:$DIR"
echo "export PATH=$PATH:$DIR" >>~/.bashrc

echo "alias gitgraph=\"git log --all --graph --decorate --oneline --simplify-by-decoration\"" >>~/.bashrc
source ~/.bashrc

#CASE INSENSITIVE TAB
# If ~./inputrc doesn't exist yet, first include the original /etc/inputrc so we don't override it
if [ ! -a ~/.inputrc ]; then echo '$include /etc/inputrc' > ~/.inputrc; fi

# Add option to ~/.inputrc to enable case-insensitive tab completion
echo 'set completion-ignore-case On' >> ~/.inputrc

